### ISSUE TITLE
Only seem to work on final mod in list?

### ISSUE THREAD

**Issue by SteveTownsend** [fireundubh/WryeBashTagGenerator#3]
I cannot see how to get this to work with other plugins than the last active  in my LO? I made a small edit to have the hotkey use the currently-highlighted plugin, attached. If I am getting this wrong please let me know and ignore the edited version. Thanks for adding the new tags and other updates.
[WryeBashTagGenerator.zip](https://github.com/fireundubh/WryeBashTagGenerator/files/6822910/WryeBashTagGenerator.zip)

**Comment by fireundubh** [comment]
That is intentional. You must load each plugin you want to tag separately from each other; therefore, the plugin you want to tag should always be last in your load order.

You should never load your entire load order. That is not how this script works, that is not how this script has ever worked, and that is not how this script even can work. Tags cannot be generated for all plugins in a load order. It is an impossible task because xEdit just isn't built that way.

If you could tag any plugin or any number of plugins at any position in your load order, you would not need a script. Wrye Bash could automate the whole process for you. The purpose of this script is generate data that Wrye Bash can't produce itself.
